<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProgressReportSeeder extends Seeder
{
    public function run()
    {
        DB::table('progress_reports')->insert([
            [
                'student_id' => 58,
                'principal_supervisor_id' => 3000,
                'lead_supervisor_id' => 3001,
                'reporting_periods_id' => 1,
                'mode_of_study' => 'Full-time',
                'goals_set' => 'Complete chapter 2 and start chapter 3',
                'progress_report' => 'Chapter 2 completed',
                'problems_issues' => 'Encountered difficulties with data analysis',
                'agreed_goals' => 'Revise data analysis and start chapter 3',
                'students_progress_rating' => 4,
                'students_completion_rate' => 40,
                'thesis_completion_percentage' => 50,
                'completion_estimation' => '2024-06-30',
                'problems_addressed' => 'Yes, support provided',
                'concerns_about_student' => 'None',
                'inadequate_aspects_comment' => 'None',
                'dir_progress_satisfaction' => true,
                'dir_registration_recommendation' => 'Continue with current plan',
                'dir_unsatisfactory_progress_comments' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => 76,
                'principal_supervisor_id' => 3001,
                'lead_supervisor_id' => 3002,
                'reporting_periods_id' => 1,
                'mode_of_study' => 'Part-time',
                'goals_set' => 'Finish literature review',
                'progress_report' => 'Literature review is halfway done',
                'problems_issues' => 'Limited access to some resources',
                'agreed_goals' => 'Complete literature review and start methodology',
                'students_progress_rating' => 3,
                'students_completion_rate' => 30,
                'thesis_completion_percentage' => 25,
                'completion_estimation' => '2025-06-30',
                'problems_addressed' => 'Library access arranged',
                'concerns_about_student' => 'Needs more focus',
                'inadequate_aspects_comment' => 'More supervision required',
                'dir_progress_satisfaction' => true,
                'dir_registration_recommendation' => 'Recommend more frequent meetings',
                'dir_unsatisfactory_progress_comments' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => 80,
                'principal_supervisor_id' => 3002,
                'lead_supervisor_id' => 3003,
                'reporting_periods_id' => 1,
                'mode_of_study' => 'Full-time',
                'goals_set' => 'Finalize data collection',
                'progress_report' => 'Data collection complete',
                'problems_issues' => 'None',
                'agreed_goals' => 'Begin data analysis',
                'students_progress_rating' => 5,
                'students_completion_rate' => 60,
                'thesis_completion_percentage' => 70,
                'completion_estimation' => '2024-12-31',
                'problems_addressed' => 'N/A',
                'concerns_about_student' => 'None',
                'inadequate_aspects_comment' => 'None',
                'dir_progress_satisfaction' => true,
                'dir_registration_recommendation' => 'On track for timely completion',
                'dir_unsatisfactory_progress_comments' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'student_id' => 85,
                'principal_supervisor_id' => 3007,
                'lead_supervisor_id' => 3008,
                'reporting_periods_id' => 2,
                'mode_of_study' => 'Full-time',
                'goals_set' => 'Complete experiment setup',
                'progress_report' => 'Experiment setup is in progress',
                'problems_issues' => 'Delay in equipment delivery',
                'agreed_goals' => 'Setup to be completed next month',
                'students_progress_rating' => 4,
                'students_completion_rate' => 35,
                'thesis_completion_percentage' => 45,
                'completion_estimation' => '2025-05-15',
                'problems_addressed' => 'Equipment issue escalated',
                'concerns_about_student' => 'Needs to manage time better',
                'inadequate_aspects_comment' => 'Will monitor closely',
                'dir_progress_satisfaction' => true,
                'dir_registration_recommendation' => 'Proceed as planned',
                'dir_unsatisfactory_progress_comments' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => 66,
                'principal_supervisor_id' => 3005,
                'lead_supervisor_id' => 3006,
                'reporting_periods_id' => 2,
                'mode_of_study' => 'Part-time',
                'goals_set' => 'Develop research methodology',
                'progress_report' => 'Methodology is under development',
                'problems_issues' => 'Struggling with theoretical framework',
                'agreed_goals' => 'Seek guidance from supervisor',
                'students_progress_rating' => 3,
                'students_completion_rate' => 20,
                'thesis_completion_percentage' => 30,
                'completion_estimation' => '2025-09-30',
                'problems_addressed' => 'Scheduled additional meetings',
                'concerns_about_student' => 'Lacks confidence in methodology',
                'inadequate_aspects_comment' => 'Encouragement and guidance needed',
                'dir_progress_satisfaction' => true,
                'dir_registration_recommendation' => 'Proceed with extra support',
                'dir_unsatisfactory_progress_comments' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => 53,
                'principal_supervisor_id' => 3015,
                'lead_supervisor_id' => 3016,
                'reporting_periods_id' => 2,
                'mode_of_study' => 'Full-time',
                'goals_set' => 'Analyze data',
                'progress_report' => 'Data analysis is ongoing',
                'problems_issues' => 'Data cleaning taking longer than expected',
                'agreed_goals' => 'Complete data analysis by next month',
                'students_progress_rating' => 4,
                'students_completion_rate' => 50,
                'thesis_completion_percentage' => 60,
                'completion_estimation' => '2024-11-30',
                'problems_addressed' => 'Additional support for data cleaning',
                'concerns_about_student' => 'None',
                'inadequate_aspects_comment' => 'None',
                'dir_progress_satisfaction' => true,
                'dir_registration_recommendation' => 'On track',
                'dir_unsatisfactory_progress_comments' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => 54,
                'principal_supervisor_id' => 3015,
                'lead_supervisor_id' => 3016,
                'reporting_periods_id' => 2,
                'mode_of_study' => 'Full-time',
                'goals_set' => 'Analyze data',
                'progress_report' => 'Data analysis is ongoing',
                'problems_issues' => 'Data cleaning taking longer than expected',
                'agreed_goals' => 'Complete data analysis by next month',
                'students_progress_rating' => 4,
                'students_completion_rate' => 50,
                'thesis_completion_percentage' => 60,
                'completion_estimation' => '2024-11-30',
                'problems_addressed' => 'Additional support for data cleaning',
                'concerns_about_student' => 'None',
                'inadequate_aspects_comment' => 'None',
                'dir_progress_satisfaction' => true,
                'dir_registration_recommendation' => 'On track',
                'dir_unsatisfactory_progress_comments' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'student_id' => 55,
                'principal_supervisor_id' => 3023,
                'lead_supervisor_id' => 3069,
                'reporting_periods_id' => 2,
                'mode_of_study' => 'Full-time',
                'goals_set' => 'Analyze data',
                'progress_report' => 'Data analysis is ongoing',
                'problems_issues' => 'Data cleaning taking longer than expected',
                'agreed_goals' => 'Complete data analysis by next month',
                'students_progress_rating' => 4,
                'students_completion_rate' => 50,
                'thesis_completion_percentage' => 60,
                'completion_estimation' => '2024-11-30',
                'problems_addressed' => 'Additional support for data cleaning',
                'concerns_about_student' => 'None',
                'inadequate_aspects_comment' => 'None',
                'dir_progress_satisfaction' => true,
                'dir_registration_recommendation' => 'On track',
                'dir_unsatisfactory_progress_comments' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
