<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SupervisorAllocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('supervisor_allocations')->insert([
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 58,
                'supervisor_id' => 3000,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 58,
                'supervisor_id' => 3001,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 76,
                'supervisor_id' => 3001,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 80,
                'supervisor_id' => 3001,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 58,
                'supervisor_id' => 3002,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 1,
                'supervisor_id' => 3003,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 66,
                'supervisor_id' => 3004,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 49,
                'supervisor_id' => 3004,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 115,
                'supervisor_id' => 3004,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 113,
                'supervisor_id' => 3004,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 66,
                'supervisor_id' => 3005,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 127,
                'supervisor_id' => 3005,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 3,
                'supervisor_id' => 3006,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 85,
                'supervisor_id' => 3007,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 51,
                'supervisor_id' => 3007,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 3,
                'supervisor_id' => 3007,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 4,
                'supervisor_id' => 3008,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 107,
                'supervisor_id' => 3008,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 4,
                'supervisor_id' => 3009,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 111,
                'supervisor_id' => 3009,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 112,
                'supervisor_id' => 3010,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 5,
                'supervisor_id' => 3010,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 70,
                'supervisor_id' => 3011,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 121,
                'supervisor_id' => 3011,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 5,
                'supervisor_id' => 3011,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 95,
                'supervisor_id' => 3011,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 74,
                'supervisor_id' => 3012,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 20,
                'supervisor_id' => 3012,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 74,
                'supervisor_id' => 3013,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 74,
                'supervisor_id' => 3014,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 116,
                'supervisor_id' => 3014,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 71,
                'supervisor_id' => 3014,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 54,
                'supervisor_id' => 3015,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 53,
                'supervisor_id' => 3015,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 54,
                'supervisor_id' => 3016,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 86,
                'supervisor_id' => 3017,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 8,
                'supervisor_id' => 3017,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 92,
                'supervisor_id' => 3017,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 100,
                'supervisor_id' => 3018,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 9,
                'supervisor_id' => 3018,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 3,
                'supervisor_id' => 3019,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 9,
                'supervisor_id' => 3019,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 10,
                'supervisor_id' => 3020,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 62,
                'supervisor_id' => 3021,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 86,
                'supervisor_id' => 3021,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 110,
                'supervisor_id' => 3021,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 10,
                'supervisor_id' => 3021,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 62,
                'supervisor_id' => 3009,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 21,
                'supervisor_id' => 3022,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 11,
                'supervisor_id' => 3022,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 13,
                'supervisor_id' => 3022,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 12,
                'supervisor_id' => 3022,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 63,
                'supervisor_id' => 3022,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 71,
                'supervisor_id' => 3022,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 21,
                'supervisor_id' => 3070,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 68,
                'supervisor_id' => 3023,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 19,
                'supervisor_id' => 3023,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 55,
                'supervisor_id' => 3023,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 59,
                'supervisor_id' => 3023,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 55,
                'supervisor_id' => 3069,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 68,
                'supervisor_id' => 3024,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 12,
                'supervisor_id' => 3025,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 13,
                'supervisor_id' => 3025,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 116,
                'supervisor_id' => 3025,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 81,
                'supervisor_id' => 3025,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 7,
                'supervisor_id' => 3025,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 13,
                'supervisor_id' => 3026,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 76,
                'supervisor_id' => 3027,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 79,
                'supervisor_id' => 3027,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 84,
                'supervisor_id' => 3027,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 64,
                'supervisor_id' => 3028,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 7,
                'supervisor_id' => 3029,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 64,
                'supervisor_id' => 3030,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 75,
                'supervisor_id' => 3030,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 65,
                'supervisor_id' => 3030,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 61,
                'supervisor_id' => 3031,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 92,
                'supervisor_id' => 3031,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 17,
                'supervisor_id' => 3031,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 106,
                'supervisor_id' => 3031,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 61,
                'supervisor_id' => 3034,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 18,
                'supervisor_id' => 3032,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 117,
                'supervisor_id' => 3032,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 18,
                'supervisor_id' => 3033,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 117,
                'supervisor_id' => 3033,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 22,
                'supervisor_id' => 3035,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 23,
                'supervisor_id' => 3036,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 24,
                'supervisor_id' => 3037,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 25,
                'supervisor_id' => 3038,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 26,
                'supervisor_id' => 3039,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 16,
                'supervisor_id' => 3040,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 120,
                'supervisor_id' => 3040,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 17,
                'supervisor_id' => 3040,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 90,
                'supervisor_id' => 3040,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 101,
                'supervisor_id' => 3041,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 11,
                'supervisor_id' => 3041,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 104,
                'supervisor_id' => 3041,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 8,
                'supervisor_id' => 3041,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 40,
                'supervisor_id' => 3041,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 6,
                'supervisor_id' => 3042,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 119,
                'supervisor_id' => 3042,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 57,
                'supervisor_id' => 3042,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 42,
                'supervisor_id' => 3043,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 93,
                'supervisor_id' => 3044,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 105,
                'supervisor_id' => 3044,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 108,
                'supervisor_id' => 3044,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 87,
                'supervisor_id' => 3045,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 46,
                'supervisor_id' => 3045,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 122,
                'supervisor_id' => 3045,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 107,
                'supervisor_id' => 3046,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 123,
                'supervisor_id' => 3046,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-01-01',
                'end_date' => '2023-12-31',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 109,
                'supervisor_id' => 3046,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 40,
                'supervisor_id' => 3047,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 48,
                'supervisor_id' => 3047,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 43,
                'supervisor_id' => 3047,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 89,
                'supervisor_id' => 3048,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 110,
                'supervisor_id' => 3048,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 113,
                'supervisor_id' => 3049,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 124,
                'supervisor_id' => 3049,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 69,
                'supervisor_id' => 3050,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 124,
                'supervisor_id' => 3050,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 120,
                'supervisor_id' => 3051,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 122,
                'supervisor_id' => 3051,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 93,
                'supervisor_id' => 3052,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 106,
                'supervisor_id' => 3052,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 98,
                'supervisor_id' => 3053,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 123,
                'supervisor_id' => 3053,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 67,
                'supervisor_id' => 3054,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 75,
                'supervisor_id' => 3054,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 43,
                'supervisor_id' => 3055,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 44,
                'supervisor_id' => 3055,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 49,
                'supervisor_id' => 3056,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 51,
                'supervisor_id' => 3056,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 128,
                'supervisor_id' => 3057,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 135,
                'supervisor_id' => 3057,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 130,
                'supervisor_id' => 3058,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 143,
                'supervisor_id' => 3058,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 130,
                'supervisor_id' => 3059,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 136,
                'supervisor_id' => 3059,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 133,
                'supervisor_id' => 3060,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 140,
                'supervisor_id' => 3060,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 138,
                'supervisor_id' => 3061,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 140,
                'supervisor_id' => 3061,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 144,
                'supervisor_id' => 3062,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 145,
                'supervisor_id' => 3062,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 148,
                'supervisor_id' => 3063,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 143,
                'supervisor_id' => 3063,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 138,
                'supervisor_id' => 3064,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 146,
                'supervisor_id' => 3064,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 142,
                'supervisor_id' => 3065,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 147,
                'supervisor_id' => 3065,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 134,
                'supervisor_id' => 3066,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 145,
                'supervisor_id' => 3066,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 111,
                'supervisor_id' => 3067,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 52,
                'supervisor_id' => 3068,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 52,
                'supervisor_id' => 3175,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 1,
                'supervisor_id' => 3175,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 3,
                'supervisor_id' => 3069,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 32,
                'supervisor_id' => 3071,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 27,
                'supervisor_id' => 3071,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 35,
                'supervisor_id' => 3071,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 2,
                'supervisor_id' => 3072,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 60,
                'supervisor_id' => 3073,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 60,
                'supervisor_id' => 3074,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 3,
                'supervisor_id' => 3075,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 28,
                'supervisor_id' => 3076,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 29,
                'supervisor_id' => 3076,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 30,
                'supervisor_id' => 3076,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 3,
                'supervisor_id' => 3077,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 6,
                'supervisor_id' => 3078,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 31,
                'supervisor_id' => 3078,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 69,
                'supervisor_id' => 3079,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 70,
                'supervisor_id' => 3080,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 16,
                'supervisor_id' => 3081,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 73,
                'supervisor_id' => 3082,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 73,
                'supervisor_id' => 3083,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 57,
                'supervisor_id' => 3084,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 59,
                'supervisor_id' => 3085,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 12,
                'supervisor_id' => 3086,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 65,
                'supervisor_id' => 3087,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 81,
                'supervisor_id' => 3088,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 63,
                'supervisor_id' => 3089,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 85,
                'supervisor_id' => 3090,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 116,
                'supervisor_id' => 3091,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 77,
                'supervisor_id' => 3092,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 77,
                'supervisor_id' => 3093,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 53,
                'supervisor_id' => 3094,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 126,
                'supervisor_id' => 3095,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 121,
                'supervisor_id' => 3096,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 126,
                'supervisor_id' => 3097,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 119,
                'supervisor_id' => 3098,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 100,
                'supervisor_id' => 3099,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 101,
                'supervisor_id' => 3100,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 104,
                'supervisor_id' => 3101,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 105,
                'supervisor_id' => 3102,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 3,
                'supervisor_id' => 3103,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 3,
                'supervisor_id' => 3104,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 108,
                'supervisor_id' => 3105,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 3,
                'supervisor_id' => 3106,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 86,
                'supervisor_id' => 3107,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 109,
                'supervisor_id' => 3108,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 114,
                'supervisor_id' => 3109,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 115,
                'supervisor_id' => 3110,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 15,
                'supervisor_id' => 3111,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 15,
                'supervisor_id' => 3112,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 67,
                'supervisor_id' => 3113,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 67,
                'supervisor_id' => 3114,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 83,
                'supervisor_id' => 3114,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 89,
                'supervisor_id' => 3115,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 87,
                'supervisor_id' => 3116,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 112,
                'supervisor_id' => 3117,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 127,
                'supervisor_id' => 3117,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 72,
                'supervisor_id' => 3118,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 14,
                'supervisor_id' => 3119,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 72,
                'supervisor_id' => 3120,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 72,
                'supervisor_id' => 3121,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 14,
                'supervisor_id' => 3122,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 78,
                'supervisor_id' => 3123,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 78,
                'supervisor_id' => 3124,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 3,
                'supervisor_id' => 3125,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 95,
                'supervisor_id' => 3126,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 97,
                'supervisor_id' => 3127,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 114,
                'supervisor_id' => 3128,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 98,
                'supervisor_id' => 3129,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 20,
                'supervisor_id' => 3130,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 90,
                'supervisor_id' => 3131,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 3,
                'supervisor_id' => 3132,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 97,
                'supervisor_id' => 3133,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 79,
                'supervisor_id' => 3134,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 83,
                'supervisor_id' => 3134,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 84,
                'supervisor_id' => 3134,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 59,
                'supervisor_id' => 3135,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 41,
                'supervisor_id' => 3136,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 47,
                'supervisor_id' => 3137,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 3,
                'supervisor_id' => 3138,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 129,
                'supervisor_id' => 3139,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 132,
                'supervisor_id' => 3140,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 136,
                'supervisor_id' => 3141,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 139,
                'supervisor_id' => 3142,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 3,
                'supervisor_id' => 3143,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 141,
                'supervisor_id' => 3144,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 146,
                'supervisor_id' => 3145,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 147,
                'supervisor_id' => 3146,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 135,
                'supervisor_id' => 3147,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 143,
                'supervisor_id' => 3148,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 142,
                'supervisor_id' => 3149,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 144,
                'supervisor_id' => 3150,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 50,
                'supervisor_id' => 3151,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 140,
                'supervisor_id' => 3151,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 3,
                'supervisor_id' => 3152,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 3,
                'supervisor_id' => 3153,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 3,
                'supervisor_id' => 3154,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 3,
                'supervisor_id' => 3155,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 80,
                'supervisor_id' => 3156,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 47,
                'supervisor_id' => 3157,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 28,
                'supervisor_id' => 3158,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 29,
                'supervisor_id' => 3159,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 30,
                'supervisor_id' => 3160,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 33,
                'supervisor_id' => 3161,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 19,
                'supervisor_id' => 3162,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 33,
                'supervisor_id' => 3163,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 36,
                'supervisor_id' => 3163,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 37,
                'supervisor_id' => 3163,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 36,
                'supervisor_id' => 3164,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 37,
                'supervisor_id' => 3164,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 31,
                'supervisor_id' => 3165,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 32,
                'supervisor_id' => 3166,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 35,
                'supervisor_id' => 3167,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 50,
                'supervisor_id' => 3168,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 27,
                'supervisor_id' => 3169,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 22,
                'supervisor_id' => 3170,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 23,
                'supervisor_id' => 3171,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 24,
                'supervisor_id' => 3172,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 25,
                'supervisor_id' => 3173,
                'status' => 'active',
            ],
            [
                'start_date' => '2023-02-01',
                'end_date' => '2023-11-30',
                'notes' => 'Contract is signed',
                'contract' => 'public/cv/Default CV.pdf',
                'student_id' => 26,
                'supervisor_id' => 3174,
                'status' => 'active',
            ] 
        ]);

    }
}
