<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('country', function (Blueprint $table) {
            $table->id();
            $table->string('country_name');
            $table->string('nationality');
            $table->string('country_code');
            $table->timestamps();
        });
         // Populate data
         $data = [
            ['country_name' =>'Afghanistan', 'nationality' => 'Afghan', 'country_code' => '93'],
            ['country_name' =>'Albania', 'nationality' => 'Albanian', 'country_code' => '355'],
            ['country_name' =>'Algeria', 'nationality' => 'Algerian', 'country_code' => '213'],
            ['country_name' =>'Andorra', 'nationality' => 'Andorran', 'country_code' => '376'],
            ['country_name' =>'Angola', 'nationality' => 'Angolan', 'country_code' => '244'],
            ['country_name' =>'Antigua and Barbuda', 'nationality' => 'Antiguan', 'country_code' => '1-268'],
            ['country_name' =>'Argentina', 'nationality' => 'Argentine', 'country_code' => '54'],
            ['country_name' =>'Armenia', 'nationality' => 'Armenian', 'country_code' => '374'],
            ['country_name' =>'Australia', 'nationality' => 'Australian', 'country_code' => '61'],
            ['country_name' =>'Austria', 'nationality' => 'Austrian', 'country_code' => '43'],
            ['country_name' =>'Azerbaijan', 'nationality' => 'Azerbaijani', 'country_code' => '994'],
            ['country_name' =>'Bahamas', 'nationality' => 'Bahamian', 'country_code' => '1-242'],
            ['country_name' =>'Bahrain', 'nationality' => 'Bahraini', 'country_code' => '973'],
            ['country_name' =>'Bangladesh', 'nationality' => 'Bangladeshi', 'country_code' => '880'],
            ['country_name' =>'Barbados', 'nationality' => 'Barbadian', 'country_code' => '1-246'],
            ['country_name' =>'Belarus', 'nationality' => 'Belarusian', 'country_code' => '375'],
            ['country_name' =>'Belgium', 'nationality' => 'Belgian', 'country_code' => '32'],
            ['country_name' =>'Belize', 'nationality' => 'Belizean', 'country_code' => '501'],
            ['country_name' =>'Benin', 'nationality' => 'Beninese', 'country_code' => '229'],
            ['country_name' =>'Bhutan', 'nationality' => 'Bhutanese', 'country_code' => '975'],
            ['country_name' =>'Bolivia', 'nationality' => 'Bolivian', 'country_code' => '591'],
            ['country_name' =>'Bosnia and Herzegovina', 'nationality' => 'Bosnian', 'country_code' => '387'],
            ['country_name' =>'Botswana', 'nationality' => 'Motswana', 'country_code' => '267'],
            ['country_name' =>'Brazil', 'nationality' => 'Brazilian', 'country_code' => '55'],
            ['country_name' =>'Brunei', 'nationality' => 'Bruneian', 'country_code' => '673'],
            ['country_name' =>'Bulgaria', 'nationality' => 'Bulgarian', 'country_code' => '359'],
            ['country_name' =>'Burkina Faso', 'nationality' => 'Burkinabe', 'country_code' => '226'],
            ['country_name' =>'Burundi', 'nationality' => 'Burundian', 'country_code' => '257'],
            ['country_name' =>'Cabo Verde', 'nationality' => 'Cabo Verdean', 'country_code' => '238'],
            ['country_name' =>'Cambodia', 'nationality' => 'Cambodian', 'country_code' => '855'],
            ['country_name' =>'Cameroon', 'nationality' => 'Cameroonian', 'country_code' => '237'],
            ['country_name' =>'Canada', 'nationality' => 'Canadian', 'country_code' => '1'],
            ['country_name' =>'Central African Republic', 'nationality' => 'Central African', 'country_code' => '236'],
            ['country_name' =>'Chad', 'nationality' => 'Chadian', 'country_code' => '235'],
            ['country_name' =>'Chile', 'nationality' => 'Chilean', 'country_code' => '56'],
            ['country_name' =>'China', 'nationality' => 'Chinese', 'country_code' => '86'],
            ['country_name' =>'Colombia', 'nationality' => 'Colombian', 'country_code' => '57'],
            ['country_name' =>'Comoros', 'nationality' => 'Comoran', 'country_code' => '269'],
            ['country_name' =>'Congo [Congo-Brazzaville]', 'nationality' => 'Congolese', 'country_code' => '242'],
            ['country_name' =>'Costa Rica', 'nationality' => 'Costa Rican', 'country_code' => '506'],
            ['country_name' =>'Cote d\'Ivoire [Ivory Coast]', 'nationality' => 'Ivorian', 'country_code' => '225'],
            ['country_name' =>'Croatia', 'nationality' => 'Croatian', 'country_code' => '385'],
            ['country_name' =>'Cuba', 'nationality' => 'Cuban', 'country_code' => '53'],
            ['country_name' =>'Cyprus', 'nationality' => 'Cypriot', 'country_code' => '357'],
            ['country_name' =>'Czech Republic', 'nationality' => 'Czech', 'country_code' => '420'],
            ['country_name' =>'Democratic Republic of the Congo [Congo-Kinshasa]', 'nationality' => 'Congolese', 'country_code' => '243'],
            ['country_name' =>'Denmark', 'nationality' => 'Danish', 'country_code' => '45'],
            ['country_name' =>'Djibouti', 'nationality' => 'Djiboutian', 'country_code' => '253'],
            ['country_name' =>'Dominica', 'nationality' => 'Dominican', 'country_code' => '1-767'],
            ['country_name' =>'Dominican Republic', 'nationality' => 'Dominican', 'country_code' => '1-809, 1-829, 1-849'],
            ['country_name' =>'East Timor [Timor-Leste]', 'nationality' => 'Timorese', 'country_code' => '670'],
            ['country_name' =>'Ecuador', 'nationality' => 'Ecuadorian', 'country_code' => '593'],
            ['country_name' =>'Egypt', 'nationality' => 'Egyptian', 'country_code' => '20'],
            ['country_name' =>'El Salvador', 'nationality' => 'Salvadoran', 'country_code' => '503'],
            ['country_name' =>'Equatorial Guinea', 'nationality' => 'Equatorial Guinean', 'country_code' => '240'],
            ['country_name' =>'Eritrea', 'nationality' => 'Eritrean', 'country_code' => '291'],
            ['country_name' =>'Estonia', 'nationality' => 'Estonian', 'country_code' => '372'],
            ['country_name' =>'Eswatini [fmr. Swaziland]', 'nationality' => 'Swazi', 'country_code' => '268'],
            ['country_name' =>'Ethiopia', 'nationality' => 'Ethiopian', 'country_code' => '251'],
            ['country_name' =>'Fiji', 'nationality' => 'Fijian', 'country_code' => '679'],
            ['country_name' =>'Finland', 'nationality' => 'Finnish', 'country_code' => '358'],
            ['country_name' =>'France', 'nationality' => 'French', 'country_code' => '33'],
            ['country_name' =>'Gabon', 'nationality' => 'Gabonese', 'country_code' => '241'],
            ['country_name' =>'Gambia', 'nationality' => 'Gambian', 'country_code' => '220'],
            ['country_name' =>'Georgia', 'nationality' => 'Georgian', 'country_code' => '995'],
            ['country_name' =>'Germany', 'nationality' => 'German', 'country_code' => '49'],
            ['country_name' =>'Ghana', 'nationality' => 'Ghanaian', 'country_code' => '233'],
            ['country_name' =>'Greece', 'nationality' => 'Greek', 'country_code' => '30'],
            ['country_name' =>'Grenada', 'nationality' => 'Grenadian', 'country_code' => '1-473'],
            ['country_name' =>'Guatemala', 'nationality' => 'Guatemalan', 'country_code' => '502'],
            ['country_name' =>'Guinea', 'nationality' => 'Guinean', 'country_code' => '224'],
            ['country_name' =>'Guinea-Bissau', 'nationality' => 'Bissau-Guinean', 'country_code' => '245'],
            ['country_name' =>'Guyana', 'nationality' => 'Guyanese', 'country_code' => '592'],
            ['country_name' =>'Haiti', 'nationality' => 'Haitian', 'country_code' => '509'],
            ['country_name' =>'Honduras', 'nationality' => 'Honduran', 'country_code' => '504'],
            ['country_name' =>'Hungary', 'nationality' => 'Hungarian', 'country_code' => '36'],
            ['country_name' =>'Iceland', 'nationality' => 'Icelander', 'country_code' => '354'],
            ['country_name' =>'India', 'nationality' => 'Indian', 'country_code' => '91'],
            ['country_name' =>'Indonesia', 'nationality' => 'Indonesian', 'country_code' => '62'],
            ['country_name' =>'Iran', 'nationality' => 'Iranian', 'country_code' => '98'],
            ['country_name' =>'Iraq', 'nationality' => 'Iraqi', 'country_code' => '964'],
            ['country_name' =>'Ireland', 'nationality' => 'Irish', 'country_code' => '353'],
            ['country_name' =>'Israel', 'nationality' => 'Israeli', 'country_code' => '972'],
            ['country_name' =>'Italy', 'nationality' => 'Italian', 'country_code' => '39'],
            ['country_name' =>'Jamaica', 'nationality' => 'Jamaican', 'country_code' => '1-876'],
            ['country_name' =>'Japan', 'nationality' => 'Japanese', 'country_code' => '81'],
            ['country_name' =>'Jordan', 'nationality' => 'Jordanian', 'country_code' => '962'],
            ['country_name' =>'Kazakhstan', 'nationality' => 'Kazakhstani', 'country_code' => '7'],
            ['country_name' =>'Kenya', 'nationality' => 'Kenyan', 'country_code' => '254'],
            ['country_name' =>'Kiribati', 'nationality' => 'I-Kiribati', 'country_code' => '686'],
            ['country_name' =>'Kosovo', 'nationality' => 'Kosovar', 'country_code' => '383'],
            ['country_name' =>'Kuwait', 'nationality' => 'Kuwaiti', 'country_code' => '965'],
            ['country_name' =>'Kyrgyzstan', 'nationality' => 'Kyrgyz', 'country_code' => '996'],
            ['country_name' =>'Laos', 'nationality' => 'Laotian', 'country_code' => '856'],
            ['country_name' =>'Latvia', 'nationality' => 'Latvian', 'country_code' => '371'],
            ['country_name' =>'Lebanon', 'nationality' => 'Lebanese', 'country_code' => '961'],
            ['country_name' =>'Lesotho', 'nationality' => 'Mosotho', 'country_code' => '266'],
            ['country_name' =>'Liberia', 'nationality' => 'Liberian', 'country_code' => '231'],
            ['country_name' =>'Libya', 'nationality' => 'Libyan', 'country_code' => '218'],
            ['country_name' =>'Liechtenstein', 'nationality' => 'Liechtensteiner', 'country_code' => '423'],
            ['country_name' =>'Lithuania', 'nationality' => 'Lithuanian', 'country_code' => '370'],
            ['country_name' =>'Luxembourg', 'nationality' => 'Luxembourger', 'country_code' => '352'],
            ['country_name' =>'Madagascar', 'nationality' => 'Malagasy', 'country_code' => '261'],
            ['country_name' =>'Malawi', 'nationality' => 'Malawian', 'country_code' => '265'],
            ['country_name' =>'Malaysia', 'nationality' => 'Malaysian', 'country_code' => '60'],
            ['country_name' =>'Maldives', 'nationality' => 'Maldivian', 'country_code' => '960'],
            ['country_name' =>'Mali', 'nationality' => 'Malian', 'country_code' => '223'],
            ['country_name' =>'Malta', 'nationality' => 'Maltese', 'country_code' => '356'],
            ['country_name' =>'Marshall Islands', 'nationality' => 'Marshallese', 'country_code' => '692'],
            ['country_name' =>'Mauritania', 'nationality' => 'Mauritanian', 'country_code' => '222'],
            ['country_name' =>'Mauritius', 'nationality' => 'Mauritian', 'country_code' => '230'],
            ['country_name' =>'Mexico', 'nationality' => 'Mexican', 'country_code' => '52'],
            ['country_name' =>'Micronesia', 'nationality' => 'Micronesian', 'country_code' => '691'],
            ['country_name' =>'Moldova', 'nationality' => 'Moldovan', 'country_code' => '373'],
            ['country_name' =>'Monaco', 'nationality' => 'Monacan', 'country_code' => '377'],
            ['country_name' =>'Mongolia', 'nationality' => 'Mongolian', 'country_code' => '976'],
            ['country_name' =>'Montenegro', 'nationality' => 'Montenegrin', 'country_code' => '382'],
            ['country_name' =>'Morocco', 'nationality' => 'Moroccan', 'country_code' => '212'],
            ['country_name' =>'Mozambique', 'nationality' => 'Mozambican', 'country_code' => '258'],
            ['country_name' =>'Myanmar [Burma]', 'nationality' => 'Burmese', 'country_code' => '95'],
            ['country_name' =>'Namibia', 'nationality' => 'Namibian', 'country_code' => '264'],
            ['country_name' =>'Nauru', 'nationality' => 'Nauruan', 'country_code' => '674'],
            ['country_name' =>'Nepal', 'nationality' => 'Nepalese', 'country_code' => '977'],
            ['country_name' =>'Netherlands', 'nationality' => 'Dutch', 'country_code' => '31'],
            ['country_name' =>'New Zealand', 'nationality' => 'New Zealander', 'country_code' => '64'],
            ['country_name' =>'Nicaragua', 'nationality' => 'Nicaraguan', 'country_code' => '505'],
            ['country_name' =>'Niger', 'nationality' => 'Nigerien', 'country_code' => '227'],
            ['country_name' =>'Nigeria', 'nationality' => 'Nigerian', 'country_code' => '234'],
            ['country_name' =>'North Korea', 'nationality' => 'North Korean', 'country_code' => '850'],
            ['country_name' =>'North Macedonia [fmr. Macedonia]', 'nationality' => 'Macedonian', 'country_code' => '389'],
            ['country_name' =>'Norway', 'nationality' => 'Norwegian', 'country_code' => '47'],
            ['country_name' =>'Oman', 'nationality' => 'Omani', 'country_code' => '968'],
            ['country_name' =>'Pakistan', 'nationality' => 'Pakistani', 'country_code' => '92'],
            ['country_name' =>'Palau', 'nationality' => 'Palauan', 'country_code' => '680'],
            ['country_name' =>'Palestine', 'nationality' => 'Palestinian', 'country_code' => '970'],
            ['country_name' =>'Panama', 'nationality' => 'Panamanian', 'country_code' => '507'],
            ['country_name' =>'Papua New Guinea', 'nationality' => 'Papua New Guinean', 'country_code' => '675'],
            ['country_name' =>'Paraguay', 'nationality' => 'Paraguayan', 'country_code' => '595'],
            ['country_name' =>'Peru', 'nationality' => 'Peruvian', 'country_code' => '51'],
            ['country_name' =>'Philippines', 'nationality' => 'Filipino', 'country_code' => '63'],
            ['country_name' =>'Poland', 'nationality' => 'Polish', 'country_code' => '48'],
            ['country_name' =>'Portugal', 'nationality' => 'Portuguese', 'country_code' => '351'],
            ['country_name' =>'Qatar', 'nationality' => 'Qatari', 'country_code' => '974'],
            ['country_name' =>'Romania', 'nationality' => 'Romanian', 'country_code' => '40'],
            ['country_name' =>'Russia', 'nationality' => 'Russian', 'country_code' => '7'],
            ['country_name' =>'Rwanda', 'nationality' => 'Rwandan', 'country_code' => '250'],
            ['country_name' =>'Saint Kitts and Nevis', 'nationality' => 'Kittitian/Nevisian', 'country_code' => '1-869'],
            ['country_name' =>'Saint Lucia', 'nationality' => 'Saint Lucian', 'country_code' => '1-758'],
            ['country_name' =>'Saint Vincent and the Grenadines', 'nationality' => 'Vincentian', 'country_code' => '1-784'],
            ['country_name' =>'Samoa', 'nationality' => 'Samoan', 'country_code' => '685'],
            ['country_name' =>'San Marino', 'nationality' => 'Sammarinese', 'country_code' => '378'],
            ['country_name' =>'Sao Tome and Principe', 'nationality' => 'Sao Tomean', 'country_code' => '239'],
            ['country_name' =>'Saudi Arabia', 'nationality' => 'Saudi Arabian', 'country_code' => '966'],
            ['country_name' =>'Senegal', 'nationality' => 'Senegalese', 'country_code' => '221'],
            ['country_name' =>'Serbia', 'nationality' => 'Serbian', 'country_code' => '381'],
            ['country_name' =>'Seychelles', 'nationality' => 'Seychellois', 'country_code' => '248'],
            ['country_name' =>'Sierra Leone', 'nationality' => 'Sierra Leonean', 'country_code' => '232'],
            ['country_name' =>'Singapore', 'nationality' => 'Singaporean', 'country_code' => '65'],
            ['country_name' =>'Slovakia', 'nationality' => 'Slovak', 'country_code' => '421'],
            ['country_name' =>'Slovenia', 'nationality' => 'Slovenian', 'country_code' => '386'],
            ['country_name' =>'Solomon Islands', 'nationality' => 'Solomon Islander', 'country_code' => '677'],
            ['country_name' =>'Somalia', 'nationality' => 'Somali', 'country_code' => '252'],
            ['country_name' =>'South Africa', 'nationality' => 'South African', 'country_code' => '27'],
            ['country_name' =>'South Korea', 'nationality' => 'South Korean', 'country_code' => '82'],
            ['country_name' =>'South Sudan', 'nationality' => 'South Sudanese', 'country_code' => '211'],
            ['country_name' =>'Spain', 'nationality' => 'Spanish', 'country_code' => '34'],
            ['country_name' =>'Sri Lanka', 'nationality' => 'Sri Lankan', 'country_code' => '94'],
            ['country_name' =>'Sudan', 'nationality' => 'Sudanese', 'country_code' => '249'],
            ['country_name' =>'Suriname', 'nationality' => 'Surinamese', 'country_code' => '597'],
            ['country_name' =>'Sweden', 'nationality' => 'Swedish', 'country_code' => '46'],
            ['country_name' =>'Switzerland', 'nationality' => 'Swiss', 'country_code' => '41'],
            ['country_name' =>'Syria', 'nationality' => 'Syrian', 'country_code' => '963'],
            ['country_name' =>'Taiwan', 'nationality' => 'Taiwanese', 'country_code' => '886'],
            ['country_name' =>'Tajikistan', 'nationality' => 'Tajik', 'country_code' => '992'],
            ['country_name' =>'Tanzania', 'nationality' => 'Tanzanian', 'country_code' => '255'],
            ['country_name' =>'Thailand', 'nationality' => 'Thai', 'country_code' => '66'],
            ['country_name' =>'Togo', 'nationality' => 'Togolese', 'country_code' => '228'],
            ['country_name' =>'Tonga', 'nationality' => 'Tongan', 'country_code' => '676'],
            ['country_name' =>'Trinidad and Tobago', 'nationality' => 'Trinidadian/Tobagonian', 'country_code' => '1-868'],
            ['country_name' =>'Tunisia', 'nationality' => 'Tunisian', 'country_code' => '216'],
            ['country_name' =>'Turkey', 'nationality' => 'Turkish', 'country_code' => '90'],
            ['country_name' =>'Turkmenistan', 'nationality' => 'Turkmen', 'country_code' => '993'],
            ['country_name' =>'Tuvalu', 'nationality' => 'Tuvaluan', 'country_code' => '688'],
            ['country_name' =>'Uganda', 'nationality' => 'Ugandan', 'country_code' => '256'],
            ['country_name' =>'Ukraine', 'nationality' => 'Ukrainian', 'country_code' => '380'],
            ['country_name' =>'United Arab Emirates', 'nationality' => 'Emirian', 'country_code' => '971'],
            ['country_name' =>'United Kingdom', 'nationality' => 'British', 'country_code' => '44'],
            ['country_name' =>'United States', 'nationality' => 'American', 'country_code' => '1'],
            ['country_name' =>'Uruguay', 'nationality' => 'Uruguayan', 'country_code' => '598'],
            ['country_name' =>'Uzbekistan', 'nationality' => 'Uzbek', 'country_code' => '998'],
            ['country_name' =>'Vanuatu', 'nationality' => 'Vanuatuan', 'country_code' => '678'],
            ['country_name' =>'Vatican City', 'nationality' => 'Citizen of Vatican City', 'country_code' => '379'],
            ['country_name' =>'Venezuela', 'nationality' => 'Venezuelan', 'country_code' => '58'],
            ['country_name' =>'Vietnam', 'nationality' => 'Vietnamese', 'country_code' => '84'],
            ['country_name' =>'Yemen', 'nationality' => 'Yemeni', 'country_code' => '967'],
            ['country_name' =>'Zambia', 'nationality' => 'Zambian', 'country_code' => '260'],
            ['country_name' =>'Zimbabwe', 'nationality' => 'Zimbabwean', 'country_code' => '263']
        ];
        

        DB::table('country')->insert($data);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('country');
    }
};
